apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-quality-fp
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/Ember1995/goitneo-mlops-fp.git
    targetRevision: final-project
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
