apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    namespace: infra-tools
    server: "https://kubernetes.default.svc"
  project: cluster-addons
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.9.10
    helm:
      valuesObject:
        grafana:
          enabled: false   
          sidecar:
            datasources:
              enabled: false   
        prometheus:
          enabled: false   
        loki:
          persistence:
            enabled: false  
        promtail:
          enabled: true    
          tolerations:
            - key: usage
              operator: Equal
              value: infrastructure
              effect: NoSchedule
        test:
          enabled: false   
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
